// Mock file for testing
// This would be generated by build_runner in a real project

import 'package:mockito/mockito.dart';
import 'package:pomodoro/app/data/services/statistics_service.dart';

class MockStatisticsService extends Mock implements StatisticsService {}