// Mock file for testing
// This would be generated by build_runner in a real project

import 'package:mockito/mockito.dart';
import 'package:pomodoro/app/data/services/pomodoro_service.dart';
import 'package:pomodoro/app/data/services/sound_service.dart';
import 'package:pomodoro/app/data/services/vibration_service.dart';
import 'package:pomodoro/app/data/services/notification_service.dart';
import 'package:pomodoro/app/data/services/background_service.dart';

class MockPomodoroService extends Mock implements PomodoroService {}
class MockSoundService extends Mock implements SoundService {}
class MockVibrationService extends Mock implements VibrationService {}
class MockNotificationService extends Mock implements NotificationService {}
class MockBackgroundService extends Mock implements BackgroundService {}