// Mock file for testing
// This would be generated by build_runner in a real project

import 'package:mockito/mockito.dart';
import 'package:pomodoro/app/core/storage_service.dart';

class MockStorageService extends Mock implements StorageService {}